[package]
name = "termsand"
version = "0.3.4"
edition = "2024"
description = "Falling sand simulation for tmux"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle-parse = "0.2.5"
anyhow = "1.0.103"
clap = { version = "4.5.15", features = ["derive"] }
console = "0.16.1"
crossterm = "0.28.1"
rand = "0.8.5"
shell-words = "1.1.1"
tempfile = "3.27.0"
term_size = "0.3.2"
unicode-width = "0.2.2"
which = "8.0.4"
